version: "3.8"
services:
  playground:
    image: salaheldin18/solang-playground-amd64:latest
    container_name: playground
    restart: always
    volumes:
      - /tmp:/tmp
    ports:
      - "9000:9000"
    runtime: sysbox-runc
